version: '3.9'
services:
    mariadb:
        image: mariadb:10.9.4
        container_name: mariadb
        restart: unless-stopped
        ports:
            - 3306:3306
        environment:
            MARIADB_ROOT_PASSWORD: ${DB_PASS}
            MARIADB_AUTO_UPGRADE: true
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - localdev
    phpmyadmin:
        image: phpmyadmin:5.2.0-apache
        container_name: phpmyadmin
        restart: unless-stopped
        ports:
            - 8080:80
        environment:
            PMA_HOST: mariadb
            PMA_USER: root
            PMA_PASSWORD: ${DB_PASS}
        depends_on:
            - mariadb
        networks:
            - localdev
networks:
    localdev:
        external: true
